config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past,     -> { where('date <  ?', DateTime.now) }
  
  belongs_to :creator, class_name: "User"
  has_many :event_attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendances, source: :attendee
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances, source: :attended_event

  def previous_events
    attended_events.past
  end

  def upcoming_events
    attended_events.upcoming
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !current_user.nil?
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in, only: [:new, :create]

  def new
    @event = current_user.events.build
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to events_path
    else
      flash.now[:danger] = "Please recheck your input"
      render 'new'
    end
  end

  private

    def event_params
      params.require(:event).permit(:title,:location,:date)
    end

    def logged_in
      redirect_to login_path unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(id: params[:session][:id])
    if user
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = "Invalid user"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to private-events"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<h3>Previous Events</h3>
<ul>
  <% @events.past.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>

<h3>Upcoming Events</h3>
<ul>
  <% @events.upcoming.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

app/views/events/show.html.erb
<h1>Event Details</h1>

<h2><%= @event.title %></h2>
<p><%= @event.location %></p>
<p><%= @event.date %></p>

<h3>Attendees</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to current_user.name, user_path(current_user) %> <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", login_path %>
    <% end %>
    <%= link_to "All events", events_path %>
    <% if logged_in? %>
      <%= link_to "New event", new_event_path %>
    <% end %>
    <% if !logged_in? %>
      <%= link_to "Sign up", new_user_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>Show</h1>

<%= @user.name %>
<%= @user.email %>

<h3>Events Created</h3>
<ul>
  <% @user.events.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>

<hr>

<h3>Previous Events</h3>
<ul>
  <% @user.previous_events.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>

<h3>Upcoming Events</h3>
<ul>
  <% @user.upcoming_events.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ul>